version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
    - ./:/usr/src/app
    - /usr/src/app/node_modules # Remove this if you have pure JS dependencies
    ports:
    - "3000:3000"
#    networks:
#    - amazeeio-network
#    - default

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: weightcore_db
      MYSQL_USER: weightcore_user
      MYSQL_PASSWORD: weightcore_password
    volumes:
#    - /mnt/sequelize-mysql-57-ramdisk:/var/lib/mysql
    - /mnt/weightcore-mysql:/var/lib/mysql
    ports:
    - "6033:3306"
    container_name: mysql-container

#networks:
#  amazeeio-network:
#    external: true
