version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
    - ./:/usr/src/app
    ports:
    - "3000:3000"
    - "8080:80"
    - "8081:8081"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: weightcore_db
      MYSQL_USER: weightcore_user
      MYSQL_PASSWORD: weightcore_password
    ports:
    - "6033:3306"
    container_name: mysql-container
